package com.ems.app.files;

// Generated Sep 22, 2015 3:02:16 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EmsCountryMaster generated by hbm2java
 */
@Entity
@Table(name = "ems_country_master", catalog = "ems")
public class EmsCountryMaster implements java.io.Serializable {

	private Long id;
	private String countryName;
	private String countryCode;
	private Set emsUserMastersForPrCountry = new HashSet(0);
	private Set emsUserMastersForSrCountry = new HashSet(0);

	public EmsCountryMaster() {
	}

	public EmsCountryMaster(String countryName, String countryCode,
			Set emsUserMastersForPrCountry, Set emsUserMastersForSrCountry) {
		this.countryName = countryName;
		this.countryCode = countryCode;
		this.emsUserMastersForPrCountry = emsUserMastersForPrCountry;
		this.emsUserMastersForSrCountry = emsUserMastersForSrCountry;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "COUNTRY_NAME", length = 50)
	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	@Column(name = "COUNTRY_CODE", length = 10)
	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "emsCountryMasterByPrCountry")
	public Set getEmsUserMastersForPrCountry() {
		return this.emsUserMastersForPrCountry;
	}

	public void setEmsUserMastersForPrCountry(Set emsUserMastersForPrCountry) {
		this.emsUserMastersForPrCountry = emsUserMastersForPrCountry;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "emsCountryMasterBySrCountry")
	public Set getEmsUserMastersForSrCountry() {
		return this.emsUserMastersForSrCountry;
	}

	public void setEmsUserMastersForSrCountry(Set emsUserMastersForSrCountry) {
		this.emsUserMastersForSrCountry = emsUserMastersForSrCountry;
	}

}
