package com.ems.app.files;

// Generated Sep 22, 2015 3:02:16 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EmsDesigMaster generated by hbm2java
 */
@Entity
@Table(name = "ems_desig_master", catalog = "ems")
public class EmsDesigMaster implements java.io.Serializable {

	private Long id;
	private EmsDesigMaster emsDesigMaster;
	private String designation;
	private Set emsDesigMasters = new HashSet(0);
	private Set emsUserDesigs = new HashSet(0);

	public EmsDesigMaster() {
	}

	public EmsDesigMaster(EmsDesigMaster emsDesigMaster, String designation,
			Set emsDesigMasters, Set emsUserDesigs) {
		this.emsDesigMaster = emsDesigMaster;
		this.designation = designation;
		this.emsDesigMasters = emsDesigMasters;
		this.emsUserDesigs = emsUserDesigs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PARENT_ID")
	public EmsDesigMaster getEmsDesigMaster() {
		return this.emsDesigMaster;
	}

	public void setEmsDesigMaster(EmsDesigMaster emsDesigMaster) {
		this.emsDesigMaster = emsDesigMaster;
	}

	@Column(name = "DESIGNATION", length = 50)
	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "emsDesigMaster")
	public Set getEmsDesigMasters() {
		return this.emsDesigMasters;
	}

	public void setEmsDesigMasters(Set emsDesigMasters) {
		this.emsDesigMasters = emsDesigMasters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "emsDesigMaster")
	public Set getEmsUserDesigs() {
		return this.emsUserDesigs;
	}

	public void setEmsUserDesigs(Set emsUserDesigs) {
		this.emsUserDesigs = emsUserDesigs;
	}

}
