package com.ems.app.files;

// Generated Sep 22, 2015 3:02:16 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EmsStateMaster generated by hbm2java
 */
@Entity
@Table(name = "ems_state_master", catalog = "ems")
public class EmsStateMaster implements java.io.Serializable {

	private Long id;
	private Long countryId;
	private String stateName;
	private Set emsUserMastersForPrState = new HashSet(0);
	private Set emsUserMastersForSrState = new HashSet(0);

	public EmsStateMaster() {
	}

	public EmsStateMaster(Long countryId, String stateName,
			Set emsUserMastersForPrState, Set emsUserMastersForSrState) {
		this.countryId = countryId;
		this.stateName = stateName;
		this.emsUserMastersForPrState = emsUserMastersForPrState;
		this.emsUserMastersForSrState = emsUserMastersForSrState;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "COUNTRY_ID")
	public Long getCountryId() {
		return this.countryId;
	}

	public void setCountryId(Long countryId) {
		this.countryId = countryId;
	}

	@Column(name = "STATE_NAME", length = 50)
	public String getStateName() {
		return this.stateName;
	}

	public void setStateName(String stateName) {
		this.stateName = stateName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "emsStateMasterByPrState")
	public Set getEmsUserMastersForPrState() {
		return this.emsUserMastersForPrState;
	}

	public void setEmsUserMastersForPrState(Set emsUserMastersForPrState) {
		this.emsUserMastersForPrState = emsUserMastersForPrState;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "emsStateMasterBySrState")
	public Set getEmsUserMastersForSrState() {
		return this.emsUserMastersForSrState;
	}

	public void setEmsUserMastersForSrState(Set emsUserMastersForSrState) {
		this.emsUserMastersForSrState = emsUserMastersForSrState;
	}

}
