package com.ems.app.files;

// Generated Sep 22, 2015 3:02:16 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmsUserDesig generated by hbm2java
 */
@Entity
@Table(name = "ems_user_desig", catalog = "ems")
public class EmsUserDesig implements java.io.Serializable {

	private Long id;
	private EmsUserMaster emsUserMasterByHrEmpId;
	private EmsUserMaster emsUserMasterByEmpId;
	private EmsUserMaster emsUserMasterByManagerEmpId;
	private EmsUserMaster emsUserMasterBySupEmpId;
	private EmsDesigMaster emsDesigMaster;

	public EmsUserDesig() {
	}

	public EmsUserDesig(EmsUserMaster emsUserMasterByHrEmpId,
			EmsUserMaster emsUserMasterByEmpId,
			EmsUserMaster emsUserMasterByManagerEmpId,
			EmsUserMaster emsUserMasterBySupEmpId, EmsDesigMaster emsDesigMaster) {
		this.emsUserMasterByHrEmpId = emsUserMasterByHrEmpId;
		this.emsUserMasterByEmpId = emsUserMasterByEmpId;
		this.emsUserMasterByManagerEmpId = emsUserMasterByManagerEmpId;
		this.emsUserMasterBySupEmpId = emsUserMasterBySupEmpId;
		this.emsDesigMaster = emsDesigMaster;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HR_EMP_ID")
	public EmsUserMaster getEmsUserMasterByHrEmpId() {
		return this.emsUserMasterByHrEmpId;
	}

	public void setEmsUserMasterByHrEmpId(EmsUserMaster emsUserMasterByHrEmpId) {
		this.emsUserMasterByHrEmpId = emsUserMasterByHrEmpId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMP_ID")
	public EmsUserMaster getEmsUserMasterByEmpId() {
		return this.emsUserMasterByEmpId;
	}

	public void setEmsUserMasterByEmpId(EmsUserMaster emsUserMasterByEmpId) {
		this.emsUserMasterByEmpId = emsUserMasterByEmpId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MANAGER_EMP_ID")
	public EmsUserMaster getEmsUserMasterByManagerEmpId() {
		return this.emsUserMasterByManagerEmpId;
	}

	public void setEmsUserMasterByManagerEmpId(
			EmsUserMaster emsUserMasterByManagerEmpId) {
		this.emsUserMasterByManagerEmpId = emsUserMasterByManagerEmpId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUP_EMP_ID")
	public EmsUserMaster getEmsUserMasterBySupEmpId() {
		return this.emsUserMasterBySupEmpId;
	}

	public void setEmsUserMasterBySupEmpId(EmsUserMaster emsUserMasterBySupEmpId) {
		this.emsUserMasterBySupEmpId = emsUserMasterBySupEmpId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_DESIG_ID")
	public EmsDesigMaster getEmsDesigMaster() {
		return this.emsDesigMaster;
	}

	public void setEmsDesigMaster(EmsDesigMaster emsDesigMaster) {
		this.emsDesigMaster = emsDesigMaster;
	}

}
