package com.ems.app.files;

// Generated Sep 22, 2015 3:02:16 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * EmsUserPwd generated by hbm2java
 */
@Entity
@Table(name = "ems_user_pwd", catalog = "ems", uniqueConstraints = @UniqueConstraint(columnNames = "USER_NAME"))
public class EmsUserPwd implements java.io.Serializable {

	private Long id;
	private EmsUserMaster emsUserMaster;
	private String userName;
	private String password;

	public EmsUserPwd() {
	}

	public EmsUserPwd(EmsUserMaster emsUserMaster, String userName,
			String password) {
		this.emsUserMaster = emsUserMaster;
		this.userName = userName;
		this.password = password;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMP_ID", nullable = false)
	public EmsUserMaster getEmsUserMaster() {
		return this.emsUserMaster;
	}

	public void setEmsUserMaster(EmsUserMaster emsUserMaster) {
		this.emsUserMaster = emsUserMaster;
	}

	@Column(name = "USER_NAME", unique = true, nullable = false, length = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "PASSWORD", nullable = false, length = 20)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
