package com.ems.app.files;

// Generated Sep 22, 2015 3:02:16 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmsUserAttendance generated by hbm2java
 */
@Entity
@Table(name = "ems_user_attendance", catalog = "ems")
public class EmsUserAttendance implements java.io.Serializable {

	private Long id;
	private EmsUserMaster emsUserMasterByCreatedBy;
	private EmsLeaveType emsLeaveType;
	private EmsUserMaster emsUserMasterByEmpId;
	private EmsUserMaster emsUserMasterByModifiedBy;
	private Date startTime;
	private Date endTime;
	private Long detailAttnId;
	private String isLeave;
	private Date createdDt;
	private Date modifiedDt;

	public EmsUserAttendance() {
	}

	public EmsUserAttendance(EmsUserMaster emsUserMasterByCreatedBy,
			EmsLeaveType emsLeaveType, EmsUserMaster emsUserMasterByEmpId,
			EmsUserMaster emsUserMasterByModifiedBy, Date startTime,
			Date endTime, Long detailAttnId, String isLeave, Date createdDt,
			Date modifiedDt) {
		this.emsUserMasterByCreatedBy = emsUserMasterByCreatedBy;
		this.emsLeaveType = emsLeaveType;
		this.emsUserMasterByEmpId = emsUserMasterByEmpId;
		this.emsUserMasterByModifiedBy = emsUserMasterByModifiedBy;
		this.startTime = startTime;
		this.endTime = endTime;
		this.detailAttnId = detailAttnId;
		this.isLeave = isLeave;
		this.createdDt = createdDt;
		this.modifiedDt = modifiedDt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public EmsUserMaster getEmsUserMasterByCreatedBy() {
		return this.emsUserMasterByCreatedBy;
	}

	public void setEmsUserMasterByCreatedBy(
			EmsUserMaster emsUserMasterByCreatedBy) {
		this.emsUserMasterByCreatedBy = emsUserMasterByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LEAVE_TYPE_ID")
	public EmsLeaveType getEmsLeaveType() {
		return this.emsLeaveType;
	}

	public void setEmsLeaveType(EmsLeaveType emsLeaveType) {
		this.emsLeaveType = emsLeaveType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMP_ID")
	public EmsUserMaster getEmsUserMasterByEmpId() {
		return this.emsUserMasterByEmpId;
	}

	public void setEmsUserMasterByEmpId(EmsUserMaster emsUserMasterByEmpId) {
		this.emsUserMasterByEmpId = emsUserMasterByEmpId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MODIFIED_BY")
	public EmsUserMaster getEmsUserMasterByModifiedBy() {
		return this.emsUserMasterByModifiedBy;
	}

	public void setEmsUserMasterByModifiedBy(
			EmsUserMaster emsUserMasterByModifiedBy) {
		this.emsUserMasterByModifiedBy = emsUserMasterByModifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "START_TIME", length = 0)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "END_TIME", length = 0)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "DETAIL_ATTN_ID")
	public Long getDetailAttnId() {
		return this.detailAttnId;
	}

	public void setDetailAttnId(Long detailAttnId) {
		this.detailAttnId = detailAttnId;
	}

	@Column(name = "IS_LEAVE", length = 1)
	public String getIsLeave() {
		return this.isLeave;
	}

	public void setIsLeave(String isLeave) {
		this.isLeave = isLeave;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DT", length = 0)
	public Date getCreatedDt() {
		return this.createdDt;
	}

	public void setCreatedDt(Date createdDt) {
		this.createdDt = createdDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFIED_DT", length = 0)
	public Date getModifiedDt() {
		return this.modifiedDt;
	}

	public void setModifiedDt(Date modifiedDt) {
		this.modifiedDt = modifiedDt;
	}

}
