package com.za.ems.app.hibernate.core.model;

// Generated Sep 22, 2015 3:02:16 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EmsCountryMaster generated by hbm2java
 */
@Entity
@Table(name = "ems_country_master", catalog = "ems")
public class EmsCountryMaster implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4585662215667241304L;
	private Long id;
	private String countryName;
	private String countryCode;
	private Set<EmsUserMaster> emsUserMastersForPrCountry = new HashSet<EmsUserMaster>(0);
	private Set<EmsUserMaster> emsUserMastersForSrCountry = new HashSet<EmsUserMaster>(0);

	public EmsCountryMaster() {
	}


	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "COUNTRY_NAME", length = 50)
	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	@Column(name = "COUNTRY_CODE", length = 10)
	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "emsCountryMasterByPrCountry")
	public Set<EmsUserMaster> getEmsUserMastersForPrCountry() {
		return this.emsUserMastersForPrCountry;
	}

	public void setEmsUserMastersForPrCountry(Set<EmsUserMaster> emsUserMastersForPrCountry) {
		this.emsUserMastersForPrCountry = emsUserMastersForPrCountry;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "emsCountryMasterBySrCountry")
	public Set<EmsUserMaster> getEmsUserMastersForSrCountry() {
		return this.emsUserMastersForSrCountry;
	}

	public void setEmsUserMastersForSrCountry(Set<EmsUserMaster> emsUserMastersForSrCountry) {
		this.emsUserMastersForSrCountry = emsUserMastersForSrCountry;
	}

}
