package com.za.ems.app.hibernate.core.model;

// Generated Sep 22, 2015 3:02:16 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EmsMasterKey generated by hbm2java
 */
@Entity
@Table(name = "ems_master_key", catalog = "ems")
public class EmsMasterKey implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5251969513423553425L;
	private long id;
	private String keyCategory;
	private String keyValue;

	public EmsMasterKey() {
	}

	public EmsMasterKey(long id) {
		this.id = id;
	}

	public EmsMasterKey(long id, String keyCategory, String keyValue) {
		this.id = id;
		this.keyCategory = keyCategory;
		this.keyValue = keyValue;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "KEY_CATEGORY", length = 50)
	public String getKeyCategory() {
		return this.keyCategory;
	}

	public void setKeyCategory(String keyCategory) {
		this.keyCategory = keyCategory;
	}

	@Column(name = "KEY_VALUE", length = 50)
	public String getKeyValue() {
		return this.keyValue;
	}

	public void setKeyValue(String keyValue) {
		this.keyValue = keyValue;
	}

}
