package com.za.ems.app.hibernate.core.model;

// Generated Sep 22, 2015 3:02:16 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EmsStateMaster generated by hbm2java
 */
@Entity
@Table(name = "ems_state_master", catalog = "ems")
public class EmsStateMaster implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2174430153607156526L;
	private Long id;
	private Long countryId;
	private String stateName;
	private Set<EmsUserMaster> emsUserMastersForPrState = new HashSet<EmsUserMaster>(0);
	private Set<EmsUserMaster> emsUserMastersForSrState = new HashSet<EmsUserMaster>(0);

	public EmsStateMaster() {
	}

	public EmsStateMaster(Long countryId, String stateName,
			Set<EmsUserMaster> emsUserMastersForPrState, Set<EmsUserMaster> emsUserMastersForSrState) {
		this.countryId = countryId;
		this.stateName = stateName;
		this.emsUserMastersForPrState = emsUserMastersForPrState;
		this.emsUserMastersForSrState = emsUserMastersForSrState;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "COUNTRY_ID")
	public Long getCountryId() {
		return this.countryId;
	}

	public void setCountryId(Long countryId) {
		this.countryId = countryId;
	}

	@Column(name = "STATE_NAME", length = 50)
	public String getStateName() {
		return this.stateName;
	}

	public void setStateName(String stateName) {
		this.stateName = stateName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "emsStateMasterByPrState")
	public Set<EmsUserMaster> getEmsUserMastersForPrState() {
		return this.emsUserMastersForPrState;
	}

	public void setEmsUserMastersForPrState(Set<EmsUserMaster> emsUserMastersForPrState) {
		this.emsUserMastersForPrState = emsUserMastersForPrState;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "emsStateMasterBySrState")
	public Set<EmsUserMaster> getEmsUserMastersForSrState() {
		return this.emsUserMastersForSrState;
	}

	public void setEmsUserMastersForSrState(Set<EmsUserMaster> emsUserMastersForSrState) {
		this.emsUserMastersForSrState = emsUserMastersForSrState;
	}

}
