package com.za.ems.app.hibernate.core.model;

// Generated Sep 22, 2015 3:02:16 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmsUserAttnDetails generated by hbm2java
 */
@Entity
@Table(name = "ems_user_attn_details", catalog = "ems")
public class EmsUserAttnDetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3631708320497382620L;
	private Long id;
	private EmsUserMaster emsUserMasterByCreatedBy;
	private EmsUserMaster emsUserMasterByEmpId;
	private Long attnId;
	private Date punchTime;
	private Date createdDt;

	public EmsUserAttnDetails() {
	}

	public EmsUserAttnDetails(EmsUserMaster emsUserMasterByCreatedBy,
			EmsUserMaster emsUserMasterByEmpId, Long attnId, Date punchTime,
			Date createdDt) {
		this.emsUserMasterByCreatedBy = emsUserMasterByCreatedBy;
		this.emsUserMasterByEmpId = emsUserMasterByEmpId;
		this.attnId = attnId;
		this.punchTime = punchTime;
		this.createdDt = createdDt;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATED_BY")
	public EmsUserMaster getEmsUserMasterByCreatedBy() {
		return this.emsUserMasterByCreatedBy;
	}

	public void setEmsUserMasterByCreatedBy(
			EmsUserMaster emsUserMasterByCreatedBy) {
		this.emsUserMasterByCreatedBy = emsUserMasterByCreatedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMP_ID")
	public EmsUserMaster getEmsUserMasterByEmpId() {
		return this.emsUserMasterByEmpId;
	}

	public void setEmsUserMasterByEmpId(EmsUserMaster emsUserMasterByEmpId) {
		this.emsUserMasterByEmpId = emsUserMasterByEmpId;
	}

	@Column(name = "ATTN_ID")
	public Long getAttnId() {
		return this.attnId;
	}

	public void setAttnId(Long attnId) {
		this.attnId = attnId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PUNCH_TIME", length = 0)
	public Date getPunchTime() {
		return this.punchTime;
	}

	public void setPunchTime(Date punchTime) {
		this.punchTime = punchTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DT", length = 0)
	public Date getCreatedDt() {
		return this.createdDt;
	}

	public void setCreatedDt(Date createdDt) {
		this.createdDt = createdDt;
	}

}
