package com.za.ems.app.hibernate.core.model;

// Generated Sep 22, 2015 3:02:16 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmsUserLogin generated by hbm2java
 */
@Entity
@Table(name = "ems_user_login", catalog = "ems")
public class EmsUserLogin implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -963247935115733662L;
	private Long id;
	private EmsUserMaster emsUserMaster;
	private Date loginTime;
	private Date logoutTime;
	private Long sessionId;

	public EmsUserLogin() {
	}

	public EmsUserLogin(EmsUserMaster emsUserMaster, Date loginTime,
			Date logoutTime, Long sessionId) {
		this.emsUserMaster = emsUserMaster;
		this.loginTime = loginTime;
		this.logoutTime = logoutTime;
		this.sessionId = sessionId;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMP_ID")
	public EmsUserMaster getEmsUserMaster() {
		return this.emsUserMaster;
	}

	public void setEmsUserMaster(EmsUserMaster emsUserMaster) {
		this.emsUserMaster = emsUserMaster;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LOGIN_TIME", length = 0)
	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LOGOUT_TIME", length = 0)
	public Date getLogoutTime() {
		return this.logoutTime;
	}

	public void setLogoutTime(Date logoutTime) {
		this.logoutTime = logoutTime;
	}

	@Column(name = "SESSION_ID")
	public Long getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(Long sessionId) {
		this.sessionId = sessionId;
	}

}
